name: Build docs

# Controls when the action will run. 
on:
  # Triggers the workflow on push only for the master branch
  push:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 🛎 Checkout repo
        uses: actions/checkout@v2
      - name: 🚧 Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: 🚧 Setup docfx
        run: choco install docfx -y
      - name: 📚 Build Docs
        working-directory: docs
        run: docfx docfx.json
        continue-on-error: false
      - name: 🚀 Publish
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gShark-docs # default: gh-pages
          publish_dir: docs/_site
          force_orphan: true
